name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
# Upload the report as a pages artifact
    - name: Upload Pages Artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: playwright-report/
